apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-broker-deployment
  labels:
    app: redis-broker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-broker
  template:
    metadata:
      labels:
        app: redis-broker
    spec:
      containers:
        - name: redis-broker-pod
          image: redis-broker-img
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
