apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis-broker
  ports:
    - protocol: TCP
      port: 6379      # Service port
      targetPort: 6379  # Container port
