services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.redis.broker
    ports:
      - "6379:6379"
  consumer1:
    build:
      context: ./consumer1
      dockerfile: Dockerfile.consumer1
    volumes:
      - ./logs:/consumer1/logs
    depends_on:
      - redis
  consumer2:
    build:
      context: ./consumer2
      dockerfile: Dockerfile.consumer2
    volumes:
      - ./logs:/consumer2/logs
    depends_on:
      - redis
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.producer
    volumes:
      - ./logs:/producer/logs
    depends_on:
      - redis
      - consumer1
      - consumer2
    ports:
      - "8080:8080"