apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: producer-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: producer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: producer-svc
            port:
              number: 8080